### ISSUE TITLE
Add custom code to onStop/onDestroy, etc

### ISSUE THREAD

**Issue by marvinroger** [tmtron/green-annotations#13]
Hi, thanks for the great annotations.

This annotation rewrites the onStart and onStop method, but there's no `beforeStart` or `beforeStop` hook. What if I previsouly had some code in these methods, along with `EventBus.getDefault().unregister(this);` ?

**Comment by tmtron** [comment]
When you look at the generated code of `MainActivity_ `, you see that `super.onStart()` is called **before** the event bus is registered:

```java
public final class MainActivity_ extends MainActivity {
    @Override
    public void onStart() {
        super.onStart();
        this.eventBus.register(this);
    }
```

So you can just implement onStart() in your activity and do stuff before the event bus will be registered:
```java
@EActivity(R.layout.activity_main)
public class MainActivity extends AppCompatActivity {

    @Override
    public void onStart() {
        Toast.makeText(getApplicationContext(), "Before register event-bus", Toast.LENGTH_SHORT).show();
        super.onStart();
  }
```
Same goes for `onStop() `
